# Generated by Django 3.2.18 on 2023-06-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sale_status',
            field=models.CharField(choices=[('판매중', '판매중'), ('예약중', '예약중'), ('판매완료', '판매완료')], default='판매중', max_length=20, null=True),
        ),
    ]
