# Generated by Django 3.2.18 on 2023-06-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0009_comment_depth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('', '카테고리'), ('일상 이야기', '일상 이야기'), ('건물 소식', '건물 소식'), ('자취 꿀팁', '자취 꿀팁'), ('같이 사요', '같이 사요')], max_length=40),
        ),
    ]
