# Generated by Django 3.2.18 on 2023-06-10 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0010_alter_post_category'),
        ('communities', '0010_auto_20230609_2216'),
    ]

    operations = [
    ]
