# Generated by Django 3.2.18 on 2023-06-13 05:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import moims.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('many', '정기모임'), ('once', '당일모임')], max_length=20)),
                ('many_datetime', models.CharField(blank=True, max_length=50, null=True)),
                ('once_datetime', models.DateTimeField(blank=True, null=True)),
                ('limit', models.IntegerField(default=1)),
                ('address', models.CharField(max_length=200)),
                ('town', models.CharField(blank=True, max_length=100, null=True)),
                ('building', models.CharField(blank=True, max_length=100, null=True)),
                ('detail_address', models.CharField(max_length=200)),
                ('kakao_url', models.CharField(max_length=300, null=True)),
                ('price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_first', models.ImageField(null=True, upload_to=moims.models.Post.post_image_path)),
                ('join_users', models.ManyToManyField(related_name='join_moims_posts', to=settings.AUTH_USER_MODEL)),
                ('like_users', models.ManyToManyField(related_name='like_moims_posts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_moims_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('depth', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('parent_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_comments', to='moims.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='moims.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_moims_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
