# Generated by Django 3.2.18 on 2023-05-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='building',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='town',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='many_datetime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='once_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
