# Generated by Django 3.2.18 on 2023-06-02 00:20

from django.db import migrations, models
import moims.models


class Migration(migrations.Migration):

    dependencies = [
        ('moims', '0002_auto_20230528_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_first',
            field=models.ImageField(null=True, upload_to=moims.models.Post.post_image_path),
        ),
    ]
