# Generated by Django 3.2.18 on 2023-06-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moims', '0003_auto_20230605_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='kakao_url',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
