# Generated by Django 3.2.18 on 2023-06-07 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moims', '0003_alter_post_image_first'),
        ('moims', '0004_post_kakao_url'),
    ]

    operations = [
    ]
