# Generated by Django 3.2.18 on 2023-06-12 05:31

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('category', models.CharField(choices=[('계정 문의', '계정 문의'), ('채팅, 알림', '채팅, 알림'), ('커뮤니티', '커뮤니티'), ('플리마켓', '플리마켓'), ('모임', '모임'), ('기타', '기타')], max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cscenter_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
