# Generated by Django 3.2.18 on 2023-06-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cscenter', '0002_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('계정 문의', '계정 문의'), ('채팅, 알림', '채팅, 알림'), ('플리마켓', '플리마켓'), ('모임', '모임'), ('다른 문제가 있어요', '다른 문제가 있어요'), ('신고하기', '신고하기')], max_length=40),
        ),
    ]
