# Generated by Django 3.2.18 on 2023-06-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cscenter', '0007_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('계정 문의', '계정 문의'), ('채팅, 알림', '채팅, 알림'), ('커뮤니티', '커뮤니티'), ('플리마켓', '플리마켓'), ('모임', '모임'), ('기타', '기타'), ('신고하기', '신고하기')], max_length=40),
        ),
    ]
