# Generated by Django 3.2.18 on 2023-06-10 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
