# Generated by Django 3.2.18 on 2023-06-10 17:15

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_first', models.ImageField(blank=True, null=True, upload_to=accounts.models.Reportimage.post_image_path)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportimages', to='accounts.userreport')),
            ],
        ),
    ]
