# Generated by Django 3.2.18 on 2023-06-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alarm'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
